// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// <define:import.meta.env>
var define_import_meta_env_default = { MODE: "production", BASE_URL: "/", DEV: false, PROD: true, SSR: false };

// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-bookings.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-bookings.ts
var list_bookings_default = defineTool({
  name: "list_bookings",
  title: "List bookings",
  description: "List PMG CRM bookings in the pipeline, optionally filtered by status.",
  inputSchema: {
    status: z.enum(["inquiry", "quoted", "booked", "shot", "delivered", "paid", "dead"]).optional().describe("Only return bookings in this pipeline status."),
    limit: z.number().int().optional().describe("Maximum rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("crm_bookings").select("id, artist_name, song_or_project, package, amount_quoted, status, shoot_date, source, notes").order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const bookings = (data ?? []).map((b) => ({
      id: b.id,
      artistName: b.artist_name,
      project: b.song_or_project ?? null,
      package: b.package ?? null,
      amountQuoted: b.amount_quoted ?? null,
      status: b.status,
      shootDate: b.shoot_date ?? null,
      source: b.source ?? null,
      notes: b.notes ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(bookings, null, 2) }],
      structuredContent: { bookings }
    };
  }
});

// src/lib/mcp/tools/list-shoots.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_shoots_default = defineTool2({
  name: "list_shoots",
  title: "List shoots",
  description: "List scheduled production shoots, optionally within a date range or by status.",
  inputSchema: {
    from: z2.string().optional().describe("Earliest shoot date, as YYYY-MM-DD."),
    to: z2.string().optional().describe("Latest shoot date, as YYYY-MM-DD."),
    status: z2.enum(["scheduled", "filming", "edit", "review", "delivered"]).optional().describe("Only return shoots in this status."),
    limit: z2.number().int().optional().describe("Maximum rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("shoots").select("id, artist_name, shoot_date, shoot_window, shoot_type, location, status, shooter, notes").order("shoot_date", { ascending: true }).limit(take);
    if (from) query = query.gte("shoot_date", from);
    if (to) query = query.lte("shoot_date", to);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const shoots = (data ?? []).map((s) => ({
      id: s.id,
      artistName: s.artist_name,
      shootDate: s.shoot_date,
      shootWindow: s.shoot_window ?? null,
      shootType: s.shoot_type,
      location: s.location ?? null,
      status: s.status,
      shooter: s.shooter ?? null,
      notes: s.notes ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(shoots, null, 2) }],
      structuredContent: { shoots }
    };
  }
});

// src/lib/mcp/tools/list-deliverables.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_deliverables_default = defineTool3({
  name: "list_deliverables",
  title: "List deliverables",
  description: "List edit deliverables and their current status, optionally filtered by status.",
  inputSchema: {
    status: z3.enum(["filmed", "editing", "reviewed", "uploaded", "published"]).optional().describe("Only return deliverables in this status."),
    limit: z3.number().int().optional().describe("Maximum rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("deliverables").select("id, shoot_id, format, status, platform, edited_by, filmed_at, delivered_at").order("updated_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const deliverables = (data ?? []).map((d) => ({
      id: d.id,
      shootId: d.shoot_id,
      format: d.format,
      status: d.status,
      platforms: (d.platform ?? []).map((p) => p),
      editedBy: d.edited_by ?? null,
      filmedAt: d.filmed_at ?? null,
      deliveredAt: d.delivered_at ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(deliverables, null, 2) }],
      structuredContent: { deliverables }
    };
  }
});

// src/lib/mcp/tools/list-artist-prospects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_artist_prospects_default = defineTool4({
  name: "list_artist_prospects",
  title: "List artist prospects",
  description: "List artist outreach prospects with their fit score and outreach status.",
  inputSchema: {
    outreach_status: z4.enum(["cold", "pitched", "replied", "discovery_call", "closed", "dead"]).optional().describe("Only return prospects in this outreach status."),
    limit: z4.number().int().optional().describe("Maximum rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ outreach_status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("artist_prospects").select(
      "id, name, city, genre, spotify_monthly_listeners, ig_followers, ig_handle, fit_score, intended_lane, outreach_status, next_followup_date"
    ).order("fit_score", { ascending: false }).limit(take);
    if (outreach_status) query = query.eq("outreach_status", outreach_status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const prospects = (data ?? []).map((p) => ({
      id: p.id,
      name: p.name,
      city: p.city ?? null,
      genre: p.genre ?? null,
      spotifyMonthlyListeners: p.spotify_monthly_listeners ?? null,
      igFollowers: p.ig_followers ?? null,
      igHandle: p.ig_handle ?? null,
      fitScore: p.fit_score ?? null,
      intendedLane: p.intended_lane ?? null,
      outreachStatus: p.outreach_status,
      nextFollowupDate: p.next_followup_date ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(prospects, null, 2) }],
      structuredContent: { prospects }
    };
  }
});

// src/lib/mcp/tools/update-booking-status.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z5 } from "npm:zod@^3.25.76";
var update_booking_status_default = defineTool5({
  name: "update_booking_status",
  title: "Update booking status",
  description: "Move a CRM booking to a different pipeline status.",
  inputSchema: {
    booking_id: z5.string().describe("The booking id to update."),
    status: z5.enum(["inquiry", "quoted", "booked", "shot", "delivered", "paid", "dead"]).describe("The new pipeline status.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ booking_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("crm_bookings").update({ status }).eq("id", booking_id).select("id, artist_name, status").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: `No booking found with id ${booking_id}` }], isError: true };
    }
    const booking = { id: data.id, artistName: data.artist_name, status: data.status };
    return {
      content: [{ type: "text", text: `${booking.artistName} is now "${booking.status}".` }],
      structuredContent: { booking }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = define_import_meta_env_default.VITE_SUPABASE_PROJECT_ID ?? "trwnqtgywfsalvismioi";
var mcp_default = defineMcp({
  name: "propmyganda-brand-launch",
  title: "Propmyganda Brand Launch",
  version: "0.1.0",
  instructions: "Tools for the Propmyganda CRM. Read bookings, shoots, deliverables, and artist prospects, and move a booking through the pipeline. Every call acts as the signed-in PMG staff member.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_bookings_default,
    list_shoots_default,
    list_deliverables_default,
    list_artist_prospects_default,
    update_booking_status_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
